apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels: 
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: gcr.io/cloud-devops-viking-test-area/myapp:probes4
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: /isalive
              port: 8888
            initialDelaySeconds: 3
            periodSeconds: 3
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.24.0
          command:
          - "/cloud_sql_proxy"
          args:
          - "-instances=cloud-devops-viking-test-area:us-central1:myapp-testdb=tcp:3306"
          - "-credential_file=/secrets/cloudsql/credentials.json"
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /secrets/cloudsql
              name: cloudsql-instance-credentials
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials

      